### ISSUE TITLE
About the released pre-trained models

### ISSUE THREAD

**Issue by iris0329** [huixiancheng/SENet#19]
Hi author, 

Thanks for your outstanding work and open source.

I have some questions about the released pre-trained models.
For 512-594, what do 512 and 594 mean respectively？

The README file mentions: First, train the model with 64x512 inputs. Then load the pre-trained model to train the model with 64x1024 inputs, and finally load the pre-trained model to train the model with 64x2048 inputs.
Is this released pre-trained model 512-594 the first step's model, and can you share the final trained model with 64x2048 input? 

I am looking forward to your reply.
Best.

**Comment by huixiancheng** [comment]
See #7. 512 mean resolution. 594 mean performance. 
Link has been updated. Released models under 1024 and 2048 resolution. “+valid” means we finetue the model on valid set.

**Comment by iris0329** [comment]
I see, thanks for your reply!
Best

**Comment by JulesSanchez** [comment]
I see that for instance, model in the 2048 folder are called "SalsaNext" are they still trained with CENet ? (in the 512 repo, it is called "SENet")

**Comment by huixiancheng** [comment]
@JulesSanchez  Hi, it's not a problem.Check the `model.txt log` or `load_state_dict` to verify it. It's just an unmodified file name. You can rename it and load it successfully. 
The reason for naming it SalsaNext is that I hadn't started writing the paper yet so I didn't change the save name in the code. SENet because that was the name of our paper when it was first submitted.
