### ISSUE TITLE
Model performance and Paper link

### ISSUE THREAD

**Issue by YoushaaMurhij** [huixiancheng/SENet#5]
Nice work! Can you please report the model performance on certain devices? I also can not find a link to the paper.

Thanks

**Comment by huixiancheng** [comment]
Hi, thank you for your interest. The paper is not upload to arxiv but there are have an original version of paper in assert. You can get model performance from it.
It should be noted that the model inference speed of FIDNET and our method in the paper is tested on RTX 3080 since I cannot get a 2080ti.

**Comment by YoushaaMurhij** [comment]
Thanks for your reply!
